### ISSUE TITLE
Package declaration

### ISSUE THREAD

**Issue by elifoster** [Strikingwolf/WolfBot#12]
Packages should be declared before the use statements for convention.

**Comment by satanicsanta** [comment]
Also you should try out perlcritic, it helps with stuff like this.

**Comment by satanicsanta** [comment]
Also you should try out perlcritic, it helps with stuff like this.

**Comment by Strikingwolf** [comment]
Thanks for the info

**Comment by Strikingwolf** [comment]
@satanicsanta I downloaded perlcritic and it isn't throwing errors at this...

**Comment by satanicsanta** [comment]
Uh, use http://perlcritic.com/

**Comment by elifoster** [comment]
Just checked, nope, it does not throw an error at this.
