### ISSUE TITLE
Argument error should have better grammar

### ISSUE THREAD

**Issue by satanicsanta** [Strikingwolf/WolfBot#6]
dafuck is this shit homie
[15:47:24] <\TheWolfBot> trajing|Mobile spy needs 1 arguments separated by whitespace

**Comment by Strikingwolf** [comment]
Bad grammar....I will fix tomorrow.

**Comment by Strikingwolf** [comment]
I won't be able to fix this today, but I *should* be able to tomorrow (I have not had access to my comp for some IRL reasons)
